# Generated by Django 4.0.2 on 2022-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Course Name')),
                ('language', models.CharField(max_length=20, verbose_name='Language')),
                ('level', models.CharField(max_length=10, verbose_name='Level')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
